# Generated by Django 4.0.4 on 2022-06-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='home/dell')),
                ('VIDEO_CHOICES', models.CharField(choices=[('GIF', 'GIF'), ('AUDIO', 'AUDIO'), ('Image', 'Image')], max_length=100)),
                ('converted_video', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
