# Generated by Django 4.0.3 on 2022-05-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIDEO_CHOICES', models.CharField(choices=[('GIF', 'GIF'), ('GPG', 'GPG')], max_length=100)),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
    ]
