# Generated by Django 4.0.4 on 2022-05-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_convert_model',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
