# Generated by Django 4.0.4 on 2022-05-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_alter_currency_convert_model_convert_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_convert_model',
            name='convert_choice',
            field=models.CharField(choices=[('usd', 'USD'), ('euro', 'EURO'), ('BritishPound', 'BritishPound'), ('astl', 'ASTL'), ('cndn', 'CNDN'), ('swissf', 'SWISSF'), ('mlysn', 'MLYSN'), ('jpns', 'JPNS'), ('chns', 'CHNS')], max_length=20),
        ),
    ]
