# Generated by Django 4.0.4 on 2022-05-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_alter_currency_convert_model_convert_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_convert_model',
            name='convert_choice',
            field=models.CharField(choices=[('usd', 'USD'), ('euro', 'EURO'), ('Astrln', 'ASTRLN'), ('Cndn', 'CNDN'), ('Sngpr', 'SNGPR'), ('SwsFrnc', 'SWSFRNC'), ('Mlysn', 'MLYSN'), ('Jpns', 'JPNS'), ('Chns', 'CHNS')], max_length=20),
        ),
    ]
