# Generated by Django 4.0.4 on 2022-05-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0011_alter_currency_convert_model_convert_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency_convert_model',
            name='current_choice',
            field=models.CharField(choices=[('usd', 'USD'), ('euro', 'EURO'), ('Astrln', 'ASTRLN'), ('Cndn', 'CNDN'), ('SingaporeDollar', 'SNGPR'), ('SwissFranc', 'SWSFRNC'), ('MalaysianRinggit', 'MLYSN'), ('JapaneseYen', 'JPNS'), ('ChineseYuanRenminbi', 'CHNS')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
