# Generated by Django 4.0.4 on 2022-05-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0012_currency_convert_model_current_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_convert_model',
            name='convert_choice',
            field=models.CharField(choices=[('usd', 'USD'), ('euro', 'EURO'), ('Astrln', 'ASTRLN'), ('Cndn', 'CNDN'), ('SingaporeDollar', 'SNGPR'), ('SwissFranc', 'SWSFRNC'), ('MalaysianRinggit', 'MLYSN'), ('JapaneseYen', 'JPNS'), ('ChineseYuanRenminbi', 'CHNS'), ('IndianRupee', 'INR')], max_length=20),
        ),
        migrations.AlterField(
            model_name='currency_convert_model',
            name='current_choice',
            field=models.CharField(choices=[('usd', 'USD'), ('euro', 'EURO'), ('Astrln', 'ASTRLN'), ('Cndn', 'CNDN'), ('SingaporeDollar', 'SNGPR'), ('SwissFranc', 'SWSFRNC'), ('MalaysianRinggit', 'MLYSN'), ('JapaneseYen', 'JPNS'), ('ChineseYuanRenminbi', 'CHNS'), ('IndianRupee', 'INR')], max_length=20),
        ),
    ]
