# Generated by Django 4.0.4 on 2022-05-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0013_alter_currency_convert_model_convert_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_convert_model',
            name='current_choice',
            field=models.CharField(choices=[('IndianRupee', 'INR')], max_length=20),
        ),
    ]
