# Generated by Django 4.0.4 on 2022-05-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0016_alter_currency_convert_model_current_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_convert_model',
            name='current_choice',
            field=models.CharField(choices=[('IndianRupee', 'INR'), ('usd', 'USD'), ('euro', 'EURO'), ('British Pound', 'BRIPOU'), ('Australian Dollar', 'AUSDOL'), ('Canadian Dollar', 'CANDOL'), ('Swiss Franc', 'SWIFc'), ('Singapore Dollar', 'SINGDOL')], max_length=20),
        ),
    ]
