# Generated by Django 4.0.4 on 2022-06-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_choices', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('html', 'HTML')], max_length=20)),
                ('file', models.FileField(upload_to='home/dell')),
                ('converted_file', models.FileField(blank=True, null=True, upload_to='')),
                ('convert_choices', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('html', 'HTML')], max_length=20)),
            ],
        ),
    ]
