# Generated by Django 4.0.4 on 2022-05-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfileupload',
            name='document_choices',
            field=models.CharField(choices=[('pdftodocs', 'pdftodocs'), ('docstopdf', 'docstopdf')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
