# Generated by Django 3.0.5 on 2022-05-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docum', '0006_alter_userfileupload_document_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfileupload',
            name='document_choices',
        ),
        migrations.AddField(
            model_name='userfileupload',
            name='convert_choices',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('html', 'HTML')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfileupload',
            name='current_choices',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('html', 'HTML')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfileupload',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
