# Generated by Django 4.0.4 on 2022-05-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConvertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/%y')),
                ('VIDEO_CHOICES', models.CharField(choices=[('GIF', 'GIF'), ('AUDIO', 'AUDIO'), ('Image', 'Image')], max_length=100)),
            ],
        ),
    ]
