# Generated by Django 4.0.4 on 2022-05-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_currency_convert_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('document_choices', models.CharField(choices=[('pdftodocs', 'PDF TO DOCX'), ('docxtohtml', 'DOCX TO HTML'), ('htmltodoc', 'HTML TO DOCX'), ('pdftohtml', 'PDF TO HTML'), ('htmltopdf', 'HTML TO PDF')], max_length=20)),
            ],
        ),
    ]
